// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/code-reviewer/watcher/github/pkg"
)

type Metrics struct {
	IncPRPublishedStub        func(string)
	incPRPublishedMutex       sync.RWMutex
	incPRPublishedArgsForCall []struct {
		arg1 string
	}
	IncPollCycleStub        func(string)
	incPollCycleMutex       sync.RWMutex
	incPollCycleArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Metrics) IncPRPublished(arg1 string) {
	fake.incPRPublishedMutex.Lock()
	fake.incPRPublishedArgsForCall = append(fake.incPRPublishedArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPRPublishedStub
	fake.recordInvocation("IncPRPublished", []interface{}{arg1})
	fake.incPRPublishedMutex.Unlock()
	if stub != nil {
		fake.IncPRPublishedStub(arg1)
	}
}

func (fake *Metrics) IncPRPublishedCallCount() int {
	fake.incPRPublishedMutex.RLock()
	defer fake.incPRPublishedMutex.RUnlock()
	return len(fake.incPRPublishedArgsForCall)
}

func (fake *Metrics) IncPRPublishedCalls(stub func(string)) {
	fake.incPRPublishedMutex.Lock()
	defer fake.incPRPublishedMutex.Unlock()
	fake.IncPRPublishedStub = stub
}

func (fake *Metrics) IncPRPublishedArgsForCall(i int) string {
	fake.incPRPublishedMutex.RLock()
	defer fake.incPRPublishedMutex.RUnlock()
	argsForCall := fake.incPRPublishedArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) IncPollCycle(arg1 string) {
	fake.incPollCycleMutex.Lock()
	fake.incPollCycleArgsForCall = append(fake.incPollCycleArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.IncPollCycleStub
	fake.recordInvocation("IncPollCycle", []interface{}{arg1})
	fake.incPollCycleMutex.Unlock()
	if stub != nil {
		fake.IncPollCycleStub(arg1)
	}
}

func (fake *Metrics) IncPollCycleCallCount() int {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	return len(fake.incPollCycleArgsForCall)
}

func (fake *Metrics) IncPollCycleCalls(stub func(string)) {
	fake.incPollCycleMutex.Lock()
	defer fake.incPollCycleMutex.Unlock()
	fake.IncPollCycleStub = stub
}

func (fake *Metrics) IncPollCycleArgsForCall(i int) string {
	fake.incPollCycleMutex.RLock()
	defer fake.incPollCycleMutex.RUnlock()
	argsForCall := fake.incPollCycleArgsForCall[i]
	return argsForCall.arg1
}

func (fake *Metrics) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Metrics) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.Metrics = new(Metrics)
