// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/code-reviewer/watcher/github/pkg/filter"
)

type TaskCreationFilter struct {
	SkipStub        func(filter.PR) bool
	skipMutex       sync.RWMutex
	skipArgsForCall []struct {
		arg1 filter.PR
	}
	skipReturns struct {
		result1 bool
	}
	skipReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskCreationFilter) Skip(arg1 filter.PR) bool {
	fake.skipMutex.Lock()
	ret, specificReturn := fake.skipReturnsOnCall[len(fake.skipArgsForCall)]
	fake.skipArgsForCall = append(fake.skipArgsForCall, struct {
		arg1 filter.PR
	}{arg1})
	stub := fake.SkipStub
	fakeReturns := fake.skipReturns
	fake.recordInvocation("Skip", []interface{}{arg1})
	fake.skipMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskCreationFilter) SkipCallCount() int {
	fake.skipMutex.RLock()
	defer fake.skipMutex.RUnlock()
	return len(fake.skipArgsForCall)
}

func (fake *TaskCreationFilter) SkipCalls(stub func(filter.PR) bool) {
	fake.skipMutex.Lock()
	defer fake.skipMutex.Unlock()
	fake.SkipStub = stub
}

func (fake *TaskCreationFilter) SkipArgsForCall(i int) filter.PR {
	fake.skipMutex.RLock()
	defer fake.skipMutex.RUnlock()
	argsForCall := fake.skipArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TaskCreationFilter) SkipReturns(result1 bool) {
	fake.skipMutex.Lock()
	defer fake.skipMutex.Unlock()
	fake.SkipStub = nil
	fake.skipReturns = struct {
		result1 bool
	}{result1}
}

func (fake *TaskCreationFilter) SkipReturnsOnCall(i int, result1 bool) {
	fake.skipMutex.Lock()
	defer fake.skipMutex.Unlock()
	fake.SkipStub = nil
	if fake.skipReturnsOnCall == nil {
		fake.skipReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.skipReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *TaskCreationFilter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskCreationFilter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ filter.TaskCreationFilter = new(TaskCreationFilter)
