// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/code-reviewer/watcher/github/pkg/trust"
)

type Trust struct {
	IsTrustedStub        func(context.Context, trust.PR) (trust.Result, error)
	isTrustedMutex       sync.RWMutex
	isTrustedArgsForCall []struct {
		arg1 context.Context
		arg2 trust.PR
	}
	isTrustedReturns struct {
		result1 trust.Result
		result2 error
	}
	isTrustedReturnsOnCall map[int]struct {
		result1 trust.Result
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Trust) IsTrusted(arg1 context.Context, arg2 trust.PR) (trust.Result, error) {
	fake.isTrustedMutex.Lock()
	ret, specificReturn := fake.isTrustedReturnsOnCall[len(fake.isTrustedArgsForCall)]
	fake.isTrustedArgsForCall = append(fake.isTrustedArgsForCall, struct {
		arg1 context.Context
		arg2 trust.PR
	}{arg1, arg2})
	stub := fake.IsTrustedStub
	fakeReturns := fake.isTrustedReturns
	fake.recordInvocation("IsTrusted", []interface{}{arg1, arg2})
	fake.isTrustedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Trust) IsTrustedCallCount() int {
	fake.isTrustedMutex.RLock()
	defer fake.isTrustedMutex.RUnlock()
	return len(fake.isTrustedArgsForCall)
}

func (fake *Trust) IsTrustedCalls(stub func(context.Context, trust.PR) (trust.Result, error)) {
	fake.isTrustedMutex.Lock()
	defer fake.isTrustedMutex.Unlock()
	fake.IsTrustedStub = stub
}

func (fake *Trust) IsTrustedArgsForCall(i int) (context.Context, trust.PR) {
	fake.isTrustedMutex.RLock()
	defer fake.isTrustedMutex.RUnlock()
	argsForCall := fake.isTrustedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Trust) IsTrustedReturns(result1 trust.Result, result2 error) {
	fake.isTrustedMutex.Lock()
	defer fake.isTrustedMutex.Unlock()
	fake.IsTrustedStub = nil
	fake.isTrustedReturns = struct {
		result1 trust.Result
		result2 error
	}{result1, result2}
}

func (fake *Trust) IsTrustedReturnsOnCall(i int, result1 trust.Result, result2 error) {
	fake.isTrustedMutex.Lock()
	defer fake.isTrustedMutex.Unlock()
	fake.IsTrustedStub = nil
	if fake.isTrustedReturnsOnCall == nil {
		fake.isTrustedReturnsOnCall = make(map[int]struct {
			result1 trust.Result
			result2 error
		})
	}
	fake.isTrustedReturnsOnCall[i] = struct {
		result1 trust.Result
		result2 error
	}{result1, result2}
}

func (fake *Trust) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Trust) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ trust.Trust = new(Trust)
