// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/code-reviewer/agent/pr-reviewer/pkg/review"
)

type Reviewer struct {
	ReviewStub        func(context.Context, string, string, string) (string, error)
	reviewMutex       sync.RWMutex
	reviewArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	reviewReturns struct {
		result1 string
		result2 error
	}
	reviewReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Reviewer) Review(arg1 context.Context, arg2 string, arg3 string, arg4 string) (string, error) {
	fake.reviewMutex.Lock()
	ret, specificReturn := fake.reviewReturnsOnCall[len(fake.reviewArgsForCall)]
	fake.reviewArgsForCall = append(fake.reviewArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.ReviewStub
	fakeReturns := fake.reviewReturns
	fake.recordInvocation("Review", []interface{}{arg1, arg2, arg3, arg4})
	fake.reviewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *Reviewer) ReviewCallCount() int {
	fake.reviewMutex.RLock()
	defer fake.reviewMutex.RUnlock()
	return len(fake.reviewArgsForCall)
}

func (fake *Reviewer) ReviewCalls(stub func(context.Context, string, string, string) (string, error)) {
	fake.reviewMutex.Lock()
	defer fake.reviewMutex.Unlock()
	fake.ReviewStub = stub
}

func (fake *Reviewer) ReviewArgsForCall(i int) (context.Context, string, string, string) {
	fake.reviewMutex.RLock()
	defer fake.reviewMutex.RUnlock()
	argsForCall := fake.reviewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *Reviewer) ReviewReturns(result1 string, result2 error) {
	fake.reviewMutex.Lock()
	defer fake.reviewMutex.Unlock()
	fake.ReviewStub = nil
	fake.reviewReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Reviewer) ReviewReturnsOnCall(i int, result1 string, result2 error) {
	fake.reviewMutex.Lock()
	defer fake.reviewMutex.Unlock()
	fake.ReviewStub = nil
	if fake.reviewReturnsOnCall == nil {
		fake.reviewReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.reviewReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *Reviewer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Reviewer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ review.Reviewer = new(Reviewer)
