// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/code-reviewer/agent/pr-reviewer/pkg/git"
)

type WorktreeManager struct {
	CreateCloneStub        func(context.Context, string, string, int) (string, error)
	createCloneMutex       sync.RWMutex
	createCloneArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	createCloneReturns struct {
		result1 string
		result2 error
	}
	createCloneReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	FetchStub        func(context.Context, string) error
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	fetchReturns struct {
		result1 error
	}
	fetchReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveCloneStub        func(context.Context, string) error
	removeCloneMutex       sync.RWMutex
	removeCloneArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	removeCloneReturns struct {
		result1 error
	}
	removeCloneReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *WorktreeManager) CreateClone(arg1 context.Context, arg2 string, arg3 string, arg4 int) (string, error) {
	fake.createCloneMutex.Lock()
	ret, specificReturn := fake.createCloneReturnsOnCall[len(fake.createCloneArgsForCall)]
	fake.createCloneArgsForCall = append(fake.createCloneArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.CreateCloneStub
	fakeReturns := fake.createCloneReturns
	fake.recordInvocation("CreateClone", []interface{}{arg1, arg2, arg3, arg4})
	fake.createCloneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *WorktreeManager) CreateCloneCallCount() int {
	fake.createCloneMutex.RLock()
	defer fake.createCloneMutex.RUnlock()
	return len(fake.createCloneArgsForCall)
}

func (fake *WorktreeManager) CreateCloneCalls(stub func(context.Context, string, string, int) (string, error)) {
	fake.createCloneMutex.Lock()
	defer fake.createCloneMutex.Unlock()
	fake.CreateCloneStub = stub
}

func (fake *WorktreeManager) CreateCloneArgsForCall(i int) (context.Context, string, string, int) {
	fake.createCloneMutex.RLock()
	defer fake.createCloneMutex.RUnlock()
	argsForCall := fake.createCloneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *WorktreeManager) CreateCloneReturns(result1 string, result2 error) {
	fake.createCloneMutex.Lock()
	defer fake.createCloneMutex.Unlock()
	fake.CreateCloneStub = nil
	fake.createCloneReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *WorktreeManager) CreateCloneReturnsOnCall(i int, result1 string, result2 error) {
	fake.createCloneMutex.Lock()
	defer fake.createCloneMutex.Unlock()
	fake.CreateCloneStub = nil
	if fake.createCloneReturnsOnCall == nil {
		fake.createCloneReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.createCloneReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *WorktreeManager) Fetch(arg1 context.Context, arg2 string) error {
	fake.fetchMutex.Lock()
	ret, specificReturn := fake.fetchReturnsOnCall[len(fake.fetchArgsForCall)]
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.FetchStub
	fakeReturns := fake.fetchReturns
	fake.recordInvocation("Fetch", []interface{}{arg1, arg2})
	fake.fetchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WorktreeManager) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *WorktreeManager) FetchCalls(stub func(context.Context, string) error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = stub
}

func (fake *WorktreeManager) FetchArgsForCall(i int) (context.Context, string) {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	argsForCall := fake.fetchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *WorktreeManager) FetchReturns(result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) FetchReturnsOnCall(i int, result1 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	if fake.fetchReturnsOnCall == nil {
		fake.fetchReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.fetchReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) RemoveClone(arg1 context.Context, arg2 string) error {
	fake.removeCloneMutex.Lock()
	ret, specificReturn := fake.removeCloneReturnsOnCall[len(fake.removeCloneArgsForCall)]
	fake.removeCloneArgsForCall = append(fake.removeCloneArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.RemoveCloneStub
	fakeReturns := fake.removeCloneReturns
	fake.recordInvocation("RemoveClone", []interface{}{arg1, arg2})
	fake.removeCloneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *WorktreeManager) RemoveCloneCallCount() int {
	fake.removeCloneMutex.RLock()
	defer fake.removeCloneMutex.RUnlock()
	return len(fake.removeCloneArgsForCall)
}

func (fake *WorktreeManager) RemoveCloneCalls(stub func(context.Context, string) error) {
	fake.removeCloneMutex.Lock()
	defer fake.removeCloneMutex.Unlock()
	fake.RemoveCloneStub = stub
}

func (fake *WorktreeManager) RemoveCloneArgsForCall(i int) (context.Context, string) {
	fake.removeCloneMutex.RLock()
	defer fake.removeCloneMutex.RUnlock()
	argsForCall := fake.removeCloneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *WorktreeManager) RemoveCloneReturns(result1 error) {
	fake.removeCloneMutex.Lock()
	defer fake.removeCloneMutex.Unlock()
	fake.RemoveCloneStub = nil
	fake.removeCloneReturns = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) RemoveCloneReturnsOnCall(i int, result1 error) {
	fake.removeCloneMutex.Lock()
	defer fake.removeCloneMutex.Unlock()
	fake.RemoveCloneStub = nil
	if fake.removeCloneReturnsOnCall == nil {
		fake.removeCloneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeCloneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *WorktreeManager) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *WorktreeManager) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ git.WorktreeManager = new(WorktreeManager)
