include $(ROOTDIR)/common.env
ifeq ($(BRANCH),prod)
include $(ROOTDIR)/prod.env
else ifeq ($(BRANCH),dev)
include $(ROOTDIR)/dev.env
else
$(error Invalid BRANCH '$(BRANCH)' — must be 'dev' or 'prod')
endif
