// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/agent/lib"
	"github.com/bborbe/code-reviewer/watcher/github/pkg/publisher"
)

type CommandPublisher struct {
	PublishCreateStub        func(context.Context, lib.CreateTaskCommand) error
	publishCreateMutex       sync.RWMutex
	publishCreateArgsForCall []struct {
		arg1 context.Context
		arg2 lib.CreateTaskCommand
	}
	publishCreateReturns struct {
		result1 error
	}
	publishCreateReturnsOnCall map[int]struct {
		result1 error
	}
	PublishUpdateFrontmatterStub        func(context.Context, lib.UpdateFrontmatterCommand) error
	publishUpdateFrontmatterMutex       sync.RWMutex
	publishUpdateFrontmatterArgsForCall []struct {
		arg1 context.Context
		arg2 lib.UpdateFrontmatterCommand
	}
	publishUpdateFrontmatterReturns struct {
		result1 error
	}
	publishUpdateFrontmatterReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CommandPublisher) PublishCreate(arg1 context.Context, arg2 lib.CreateTaskCommand) error {
	fake.publishCreateMutex.Lock()
	ret, specificReturn := fake.publishCreateReturnsOnCall[len(fake.publishCreateArgsForCall)]
	fake.publishCreateArgsForCall = append(fake.publishCreateArgsForCall, struct {
		arg1 context.Context
		arg2 lib.CreateTaskCommand
	}{arg1, arg2})
	stub := fake.PublishCreateStub
	fakeReturns := fake.publishCreateReturns
	fake.recordInvocation("PublishCreate", []interface{}{arg1, arg2})
	fake.publishCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommandPublisher) PublishCreateCallCount() int {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	return len(fake.publishCreateArgsForCall)
}

func (fake *CommandPublisher) PublishCreateCalls(stub func(context.Context, lib.CreateTaskCommand) error) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = stub
}

func (fake *CommandPublisher) PublishCreateArgsForCall(i int) (context.Context, lib.CreateTaskCommand) {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	argsForCall := fake.publishCreateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CommandPublisher) PublishCreateReturns(result1 error) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	fake.publishCreateReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommandPublisher) PublishCreateReturnsOnCall(i int, result1 error) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	if fake.publishCreateReturnsOnCall == nil {
		fake.publishCreateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishCreateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommandPublisher) PublishUpdateFrontmatter(arg1 context.Context, arg2 lib.UpdateFrontmatterCommand) error {
	fake.publishUpdateFrontmatterMutex.Lock()
	ret, specificReturn := fake.publishUpdateFrontmatterReturnsOnCall[len(fake.publishUpdateFrontmatterArgsForCall)]
	fake.publishUpdateFrontmatterArgsForCall = append(fake.publishUpdateFrontmatterArgsForCall, struct {
		arg1 context.Context
		arg2 lib.UpdateFrontmatterCommand
	}{arg1, arg2})
	stub := fake.PublishUpdateFrontmatterStub
	fakeReturns := fake.publishUpdateFrontmatterReturns
	fake.recordInvocation("PublishUpdateFrontmatter", []interface{}{arg1, arg2})
	fake.publishUpdateFrontmatterMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommandPublisher) PublishUpdateFrontmatterCallCount() int {
	fake.publishUpdateFrontmatterMutex.RLock()
	defer fake.publishUpdateFrontmatterMutex.RUnlock()
	return len(fake.publishUpdateFrontmatterArgsForCall)
}

func (fake *CommandPublisher) PublishUpdateFrontmatterCalls(stub func(context.Context, lib.UpdateFrontmatterCommand) error) {
	fake.publishUpdateFrontmatterMutex.Lock()
	defer fake.publishUpdateFrontmatterMutex.Unlock()
	fake.PublishUpdateFrontmatterStub = stub
}

func (fake *CommandPublisher) PublishUpdateFrontmatterArgsForCall(i int) (context.Context, lib.UpdateFrontmatterCommand) {
	fake.publishUpdateFrontmatterMutex.RLock()
	defer fake.publishUpdateFrontmatterMutex.RUnlock()
	argsForCall := fake.publishUpdateFrontmatterArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CommandPublisher) PublishUpdateFrontmatterReturns(result1 error) {
	fake.publishUpdateFrontmatterMutex.Lock()
	defer fake.publishUpdateFrontmatterMutex.Unlock()
	fake.PublishUpdateFrontmatterStub = nil
	fake.publishUpdateFrontmatterReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommandPublisher) PublishUpdateFrontmatterReturnsOnCall(i int, result1 error) {
	fake.publishUpdateFrontmatterMutex.Lock()
	defer fake.publishUpdateFrontmatterMutex.Unlock()
	fake.PublishUpdateFrontmatterStub = nil
	if fake.publishUpdateFrontmatterReturnsOnCall == nil {
		fake.publishUpdateFrontmatterReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.publishUpdateFrontmatterReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommandPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CommandPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ publisher.CommandPublisher = new(CommandPublisher)
