// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/pr-reviewer/pkg/bitbucket"
)

type BitbucketClient struct {
	ApproveStub        func(context.Context, string, string, string, int) error
	approveMutex       sync.RWMutex
	approveArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
	}
	approveReturns struct {
		result1 error
	}
	approveReturnsOnCall map[int]struct {
		result1 error
	}
	GetPRBranchStub        func(context.Context, string, string, string, int) (string, error)
	getPRBranchMutex       sync.RWMutex
	getPRBranchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
	}
	getPRBranchReturns struct {
		result1 string
		result2 error
	}
	getPRBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetProfileStub        func(context.Context, string) (bitbucket.Profile, error)
	getProfileMutex       sync.RWMutex
	getProfileArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getProfileReturns struct {
		result1 bitbucket.Profile
		result2 error
	}
	getProfileReturnsOnCall map[int]struct {
		result1 bitbucket.Profile
		result2 error
	}
	NeedsWorkStub        func(context.Context, string, string, string, int, string) error
	needsWorkMutex       sync.RWMutex
	needsWorkArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
		arg6 string
	}
	needsWorkReturns struct {
		result1 error
	}
	needsWorkReturnsOnCall map[int]struct {
		result1 error
	}
	PostCommentStub        func(context.Context, string, string, string, int, string) error
	postCommentMutex       sync.RWMutex
	postCommentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
		arg6 string
	}
	postCommentReturns struct {
		result1 error
	}
	postCommentReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *BitbucketClient) Approve(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 int) error {
	fake.approveMutex.Lock()
	ret, specificReturn := fake.approveReturnsOnCall[len(fake.approveArgsForCall)]
	fake.approveArgsForCall = append(fake.approveArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ApproveStub
	fakeReturns := fake.approveReturns
	fake.recordInvocation("Approve", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.approveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *BitbucketClient) ApproveCallCount() int {
	fake.approveMutex.RLock()
	defer fake.approveMutex.RUnlock()
	return len(fake.approveArgsForCall)
}

func (fake *BitbucketClient) ApproveCalls(stub func(context.Context, string, string, string, int) error) {
	fake.approveMutex.Lock()
	defer fake.approveMutex.Unlock()
	fake.ApproveStub = stub
}

func (fake *BitbucketClient) ApproveArgsForCall(i int) (context.Context, string, string, string, int) {
	fake.approveMutex.RLock()
	defer fake.approveMutex.RUnlock()
	argsForCall := fake.approveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *BitbucketClient) ApproveReturns(result1 error) {
	fake.approveMutex.Lock()
	defer fake.approveMutex.Unlock()
	fake.ApproveStub = nil
	fake.approveReturns = struct {
		result1 error
	}{result1}
}

func (fake *BitbucketClient) ApproveReturnsOnCall(i int, result1 error) {
	fake.approveMutex.Lock()
	defer fake.approveMutex.Unlock()
	fake.ApproveStub = nil
	if fake.approveReturnsOnCall == nil {
		fake.approveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.approveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *BitbucketClient) GetPRBranch(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 int) (string, error) {
	fake.getPRBranchMutex.Lock()
	ret, specificReturn := fake.getPRBranchReturnsOnCall[len(fake.getPRBranchArgsForCall)]
	fake.getPRBranchArgsForCall = append(fake.getPRBranchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.GetPRBranchStub
	fakeReturns := fake.getPRBranchReturns
	fake.recordInvocation("GetPRBranch", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.getPRBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BitbucketClient) GetPRBranchCallCount() int {
	fake.getPRBranchMutex.RLock()
	defer fake.getPRBranchMutex.RUnlock()
	return len(fake.getPRBranchArgsForCall)
}

func (fake *BitbucketClient) GetPRBranchCalls(stub func(context.Context, string, string, string, int) (string, error)) {
	fake.getPRBranchMutex.Lock()
	defer fake.getPRBranchMutex.Unlock()
	fake.GetPRBranchStub = stub
}

func (fake *BitbucketClient) GetPRBranchArgsForCall(i int) (context.Context, string, string, string, int) {
	fake.getPRBranchMutex.RLock()
	defer fake.getPRBranchMutex.RUnlock()
	argsForCall := fake.getPRBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *BitbucketClient) GetPRBranchReturns(result1 string, result2 error) {
	fake.getPRBranchMutex.Lock()
	defer fake.getPRBranchMutex.Unlock()
	fake.GetPRBranchStub = nil
	fake.getPRBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *BitbucketClient) GetPRBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.getPRBranchMutex.Lock()
	defer fake.getPRBranchMutex.Unlock()
	fake.GetPRBranchStub = nil
	if fake.getPRBranchReturnsOnCall == nil {
		fake.getPRBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getPRBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *BitbucketClient) GetProfile(arg1 context.Context, arg2 string) (bitbucket.Profile, error) {
	fake.getProfileMutex.Lock()
	ret, specificReturn := fake.getProfileReturnsOnCall[len(fake.getProfileArgsForCall)]
	fake.getProfileArgsForCall = append(fake.getProfileArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetProfileStub
	fakeReturns := fake.getProfileReturns
	fake.recordInvocation("GetProfile", []interface{}{arg1, arg2})
	fake.getProfileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *BitbucketClient) GetProfileCallCount() int {
	fake.getProfileMutex.RLock()
	defer fake.getProfileMutex.RUnlock()
	return len(fake.getProfileArgsForCall)
}

func (fake *BitbucketClient) GetProfileCalls(stub func(context.Context, string) (bitbucket.Profile, error)) {
	fake.getProfileMutex.Lock()
	defer fake.getProfileMutex.Unlock()
	fake.GetProfileStub = stub
}

func (fake *BitbucketClient) GetProfileArgsForCall(i int) (context.Context, string) {
	fake.getProfileMutex.RLock()
	defer fake.getProfileMutex.RUnlock()
	argsForCall := fake.getProfileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *BitbucketClient) GetProfileReturns(result1 bitbucket.Profile, result2 error) {
	fake.getProfileMutex.Lock()
	defer fake.getProfileMutex.Unlock()
	fake.GetProfileStub = nil
	fake.getProfileReturns = struct {
		result1 bitbucket.Profile
		result2 error
	}{result1, result2}
}

func (fake *BitbucketClient) GetProfileReturnsOnCall(i int, result1 bitbucket.Profile, result2 error) {
	fake.getProfileMutex.Lock()
	defer fake.getProfileMutex.Unlock()
	fake.GetProfileStub = nil
	if fake.getProfileReturnsOnCall == nil {
		fake.getProfileReturnsOnCall = make(map[int]struct {
			result1 bitbucket.Profile
			result2 error
		})
	}
	fake.getProfileReturnsOnCall[i] = struct {
		result1 bitbucket.Profile
		result2 error
	}{result1, result2}
}

func (fake *BitbucketClient) NeedsWork(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 int, arg6 string) error {
	fake.needsWorkMutex.Lock()
	ret, specificReturn := fake.needsWorkReturnsOnCall[len(fake.needsWorkArgsForCall)]
	fake.needsWorkArgsForCall = append(fake.needsWorkArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.NeedsWorkStub
	fakeReturns := fake.needsWorkReturns
	fake.recordInvocation("NeedsWork", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.needsWorkMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *BitbucketClient) NeedsWorkCallCount() int {
	fake.needsWorkMutex.RLock()
	defer fake.needsWorkMutex.RUnlock()
	return len(fake.needsWorkArgsForCall)
}

func (fake *BitbucketClient) NeedsWorkCalls(stub func(context.Context, string, string, string, int, string) error) {
	fake.needsWorkMutex.Lock()
	defer fake.needsWorkMutex.Unlock()
	fake.NeedsWorkStub = stub
}

func (fake *BitbucketClient) NeedsWorkArgsForCall(i int) (context.Context, string, string, string, int, string) {
	fake.needsWorkMutex.RLock()
	defer fake.needsWorkMutex.RUnlock()
	argsForCall := fake.needsWorkArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *BitbucketClient) NeedsWorkReturns(result1 error) {
	fake.needsWorkMutex.Lock()
	defer fake.needsWorkMutex.Unlock()
	fake.NeedsWorkStub = nil
	fake.needsWorkReturns = struct {
		result1 error
	}{result1}
}

func (fake *BitbucketClient) NeedsWorkReturnsOnCall(i int, result1 error) {
	fake.needsWorkMutex.Lock()
	defer fake.needsWorkMutex.Unlock()
	fake.NeedsWorkStub = nil
	if fake.needsWorkReturnsOnCall == nil {
		fake.needsWorkReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.needsWorkReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *BitbucketClient) PostComment(arg1 context.Context, arg2 string, arg3 string, arg4 string, arg5 int, arg6 string) error {
	fake.postCommentMutex.Lock()
	ret, specificReturn := fake.postCommentReturnsOnCall[len(fake.postCommentArgsForCall)]
	fake.postCommentArgsForCall = append(fake.postCommentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
		arg5 int
		arg6 string
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.PostCommentStub
	fakeReturns := fake.postCommentReturns
	fake.recordInvocation("PostComment", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.postCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *BitbucketClient) PostCommentCallCount() int {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	return len(fake.postCommentArgsForCall)
}

func (fake *BitbucketClient) PostCommentCalls(stub func(context.Context, string, string, string, int, string) error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = stub
}

func (fake *BitbucketClient) PostCommentArgsForCall(i int) (context.Context, string, string, string, int, string) {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	argsForCall := fake.postCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *BitbucketClient) PostCommentReturns(result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	fake.postCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *BitbucketClient) PostCommentReturnsOnCall(i int, result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	if fake.postCommentReturnsOnCall == nil {
		fake.postCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *BitbucketClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *BitbucketClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ bitbucket.Client = new(BitbucketClient)
