// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/code-reviewer/pkg/github"
	"github.com/bborbe/code-reviewer/pkg/verdict"
)

type GitHubClient struct {
	GetPRBranchesStub        func(context.Context, string, string, int) (github.PRBranches, error)
	getPRBranchesMutex       sync.RWMutex
	getPRBranchesArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	getPRBranchesReturns struct {
		result1 github.PRBranches
		result2 error
	}
	getPRBranchesReturnsOnCall map[int]struct {
		result1 github.PRBranches
		result2 error
	}
	PostCommentStub        func(context.Context, string, string, int, string) error
	postCommentMutex       sync.RWMutex
	postCommentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	postCommentReturns struct {
		result1 error
	}
	postCommentReturnsOnCall map[int]struct {
		result1 error
	}
	SubmitReviewStub        func(context.Context, string, string, int, string, verdict.Verdict) error
	submitReviewMutex       sync.RWMutex
	submitReviewArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
		arg6 verdict.Verdict
	}
	submitReviewReturns struct {
		result1 error
	}
	submitReviewReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetPRBranches(arg1 context.Context, arg2 string, arg3 string, arg4 int) (github.PRBranches, error) {
	fake.getPRBranchesMutex.Lock()
	ret, specificReturn := fake.getPRBranchesReturnsOnCall[len(fake.getPRBranchesArgsForCall)]
	fake.getPRBranchesArgsForCall = append(fake.getPRBranchesArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPRBranchesStub
	fakeReturns := fake.getPRBranchesReturns
	fake.recordInvocation("GetPRBranches", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPRBranchesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetPRBranchesCallCount() int {
	fake.getPRBranchesMutex.RLock()
	defer fake.getPRBranchesMutex.RUnlock()
	return len(fake.getPRBranchesArgsForCall)
}

func (fake *GitHubClient) GetPRBranchesCalls(stub func(context.Context, string, string, int) (github.PRBranches, error)) {
	fake.getPRBranchesMutex.Lock()
	defer fake.getPRBranchesMutex.Unlock()
	fake.GetPRBranchesStub = stub
}

func (fake *GitHubClient) GetPRBranchesArgsForCall(i int) (context.Context, string, string, int) {
	fake.getPRBranchesMutex.RLock()
	defer fake.getPRBranchesMutex.RUnlock()
	argsForCall := fake.getPRBranchesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) GetPRBranchesReturns(result1 github.PRBranches, result2 error) {
	fake.getPRBranchesMutex.Lock()
	defer fake.getPRBranchesMutex.Unlock()
	fake.GetPRBranchesStub = nil
	fake.getPRBranchesReturns = struct {
		result1 github.PRBranches
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRBranchesReturnsOnCall(i int, result1 github.PRBranches, result2 error) {
	fake.getPRBranchesMutex.Lock()
	defer fake.getPRBranchesMutex.Unlock()
	fake.GetPRBranchesStub = nil
	if fake.getPRBranchesReturnsOnCall == nil {
		fake.getPRBranchesReturnsOnCall = make(map[int]struct {
			result1 github.PRBranches
			result2 error
		})
	}
	fake.getPRBranchesReturnsOnCall[i] = struct {
		result1 github.PRBranches
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) PostComment(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) error {
	fake.postCommentMutex.Lock()
	ret, specificReturn := fake.postCommentReturnsOnCall[len(fake.postCommentArgsForCall)]
	fake.postCommentArgsForCall = append(fake.postCommentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PostCommentStub
	fakeReturns := fake.postCommentReturns
	fake.recordInvocation("PostComment", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.postCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) PostCommentCallCount() int {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	return len(fake.postCommentArgsForCall)
}

func (fake *GitHubClient) PostCommentCalls(stub func(context.Context, string, string, int, string) error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = stub
}

func (fake *GitHubClient) PostCommentArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	argsForCall := fake.postCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *GitHubClient) PostCommentReturns(result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	fake.postCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) PostCommentReturnsOnCall(i int, result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	if fake.postCommentReturnsOnCall == nil {
		fake.postCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) SubmitReview(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string, arg6 verdict.Verdict) error {
	fake.submitReviewMutex.Lock()
	ret, specificReturn := fake.submitReviewReturnsOnCall[len(fake.submitReviewArgsForCall)]
	fake.submitReviewArgsForCall = append(fake.submitReviewArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
		arg6 verdict.Verdict
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.SubmitReviewStub
	fakeReturns := fake.submitReviewReturns
	fake.recordInvocation("SubmitReview", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.submitReviewMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) SubmitReviewCallCount() int {
	fake.submitReviewMutex.RLock()
	defer fake.submitReviewMutex.RUnlock()
	return len(fake.submitReviewArgsForCall)
}

func (fake *GitHubClient) SubmitReviewCalls(stub func(context.Context, string, string, int, string, verdict.Verdict) error) {
	fake.submitReviewMutex.Lock()
	defer fake.submitReviewMutex.Unlock()
	fake.SubmitReviewStub = stub
}

func (fake *GitHubClient) SubmitReviewArgsForCall(i int) (context.Context, string, string, int, string, verdict.Verdict) {
	fake.submitReviewMutex.RLock()
	defer fake.submitReviewMutex.RUnlock()
	argsForCall := fake.submitReviewArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *GitHubClient) SubmitReviewReturns(result1 error) {
	fake.submitReviewMutex.Lock()
	defer fake.submitReviewMutex.Unlock()
	fake.SubmitReviewStub = nil
	fake.submitReviewReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) SubmitReviewReturnsOnCall(i int, result1 error) {
	fake.submitReviewMutex.Lock()
	defer fake.submitReviewMutex.Unlock()
	fake.SubmitReviewStub = nil
	if fake.submitReviewReturnsOnCall == nil {
		fake.submitReviewReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.submitReviewReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ github.Client = new(GitHubClient)
