// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/pr-reviewer/pkg/github"
)

type GitHubClient struct {
	GetPRBranchStub        func(context.Context, string, string, int) (string, error)
	getPRBranchMutex       sync.RWMutex
	getPRBranchArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}
	getPRBranchReturns struct {
		result1 string
		result2 error
	}
	getPRBranchReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	PostCommentStub        func(context.Context, string, string, int, string) error
	postCommentMutex       sync.RWMutex
	postCommentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}
	postCommentReturns struct {
		result1 error
	}
	postCommentReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetPRBranch(arg1 context.Context, arg2 string, arg3 string, arg4 int) (string, error) {
	fake.getPRBranchMutex.Lock()
	ret, specificReturn := fake.getPRBranchReturnsOnCall[len(fake.getPRBranchArgsForCall)]
	fake.getPRBranchArgsForCall = append(fake.getPRBranchArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetPRBranchStub
	fakeReturns := fake.getPRBranchReturns
	fake.recordInvocation("GetPRBranch", []interface{}{arg1, arg2, arg3, arg4})
	fake.getPRBranchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetPRBranchCallCount() int {
	fake.getPRBranchMutex.RLock()
	defer fake.getPRBranchMutex.RUnlock()
	return len(fake.getPRBranchArgsForCall)
}

func (fake *GitHubClient) GetPRBranchCalls(stub func(context.Context, string, string, int) (string, error)) {
	fake.getPRBranchMutex.Lock()
	defer fake.getPRBranchMutex.Unlock()
	fake.GetPRBranchStub = stub
}

func (fake *GitHubClient) GetPRBranchArgsForCall(i int) (context.Context, string, string, int) {
	fake.getPRBranchMutex.RLock()
	defer fake.getPRBranchMutex.RUnlock()
	argsForCall := fake.getPRBranchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *GitHubClient) GetPRBranchReturns(result1 string, result2 error) {
	fake.getPRBranchMutex.Lock()
	defer fake.getPRBranchMutex.Unlock()
	fake.GetPRBranchStub = nil
	fake.getPRBranchReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetPRBranchReturnsOnCall(i int, result1 string, result2 error) {
	fake.getPRBranchMutex.Lock()
	defer fake.getPRBranchMutex.Unlock()
	fake.GetPRBranchStub = nil
	if fake.getPRBranchReturnsOnCall == nil {
		fake.getPRBranchReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getPRBranchReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) PostComment(arg1 context.Context, arg2 string, arg3 string, arg4 int, arg5 string) error {
	fake.postCommentMutex.Lock()
	ret, specificReturn := fake.postCommentReturnsOnCall[len(fake.postCommentArgsForCall)]
	fake.postCommentArgsForCall = append(fake.postCommentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 int
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.PostCommentStub
	fakeReturns := fake.postCommentReturns
	fake.recordInvocation("PostComment", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.postCommentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *GitHubClient) PostCommentCallCount() int {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	return len(fake.postCommentArgsForCall)
}

func (fake *GitHubClient) PostCommentCalls(stub func(context.Context, string, string, int, string) error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = stub
}

func (fake *GitHubClient) PostCommentArgsForCall(i int) (context.Context, string, string, int, string) {
	fake.postCommentMutex.RLock()
	defer fake.postCommentMutex.RUnlock()
	argsForCall := fake.postCommentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *GitHubClient) PostCommentReturns(result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	fake.postCommentReturns = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) PostCommentReturnsOnCall(i int, result1 error) {
	fake.postCommentMutex.Lock()
	defer fake.postCommentMutex.Unlock()
	fake.PostCommentStub = nil
	if fake.postCommentReturnsOnCall == nil {
		fake.postCommentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.postCommentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ github.Client = new(GitHubClient)
