apiVersion: agent.benjamin-borbe.de/v1
kind: Config
metadata:
  name: agent-pr-reviewer
  namespace: '{{ "NAMESPACE" | env }}'
spec:
  assignee: pr-reviewer-agent
  priorityClassName: agent-pr-reviewer
  image: '{{"DOCKER_REGISTRY" | env}}/agent-pr-reviewer'
  heartbeat: 5m
  secretName: agent-pr-reviewer
  volumeClaim: agent-pr-reviewer
  volumeMountPath: /home/claude/.claude
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 2Gi
    limits:
      cpu: 500m
      memory: 1Gi
      ephemeral-storage: 2Gi
