apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: agent-pr-reviewer
  namespace: '{{ "NAMESPACE" | env }}'
data:
  SENTRY_DSN: '{{ "SENTRY_DSN_KEY" | env | teamvaultUrl | base64 }}'
  GH_TOKEN: '{{ "PR_REVIEWER_GITHUB_TOKEN_KEY" | env | teamvaultPassword | base64 }}'
